### ISSUE TITLE
Error from cleaner sprite when trying to pick up crates from fishing net

### ISSUE THREAD

**Issue by quang-duc-000** [Aidanamite/Benevolent-Sprites#1]
![image](https://github.com/Aidanamite/Benevolent-Sprites/assets/23278964/e48b49c9-9b27-42b7-a687-43e7b2f44c60)
I got this error when the cleaner sprite was trying to pick up crates from a fishing net
Can you fix it? @Aidanamite

**Comment by Aidanamite** [comment]
that's an error I didn't expect to see.... the vietnamese language mod is having an issue with the sprite's mod...
Given the error occured directly inside the vietnamese mod, I think what's happened is the language mod doesn't account for something being missing that the base-game handles fine. I think this issue would be best fixed in the vietnamese mod
